services:
  - type: web
    name: goodfit-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn goodfit_api.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: DATABASE_URL
        fromDatabase:
          name: goodfit-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: goodfit_api.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: True

databases:
  - name: goodfit-db
    databaseName: goodfit_production
    user: goodfit_user
    plan: free
